# Generated by Django 3.1.7 on 2021-03-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='notebook',
            table=None,
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='draft_user',
        ),
    ]
